### ISSUE TITLE
Not minified JavaScript files

### ISSUE THREAD

**Issue by Ky7m** [Microsoft/Docs#52]
On the home page (https://docs.microsoft.com/en-us/) there are some JS files that are not minified :

- https://docs.microsoft.com/_themes/docs.theme/master/en-us/_themes/global/js/global.min.js?v=160 
- https://docs.microsoft.com/_themes/docs.theme/master/en-us/_themes/global/js/worker.js?v=160

Compression of these files can save around 70 kb.

**Comment by Ky7m** [comment]
@EisenbergEffect is it a right place to post some kind of issue?

**Comment by DuncanmaMSFT** [comment]
@Ky7m This is a great place, thanks. We'll resolve this in the near future, we've recently moved to a new bundling pipeline but aren't yet minifying these files. Thanks for letting us know!

**Comment by Ky7m** [comment]
Got it! Thanks!
